=== szumaster100/backup-storage/Maps/configs/droplist.xsd
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Cleroth (Moblix) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xsd:complexType name="droplist_t">
		<xsd:sequence>
			<xsd:element name="npc_t" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="tier_t" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="item_t" maxOccurs="unbounded">
										<xsd:complexType>
											<xsd:attribute name="name" type="xsd:string" use="required"/>
											<xsd:attribute name="prob" type="xsd:positiveInteger" use="required"/>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
								<xsd:attribute name="prob" type="xsd:positiveInteger" use="required"/>
								<xsd:attribute name="type" type="xsd:string" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="name" type="xsd:string" use="required"/>
					<xsd:attribute name="num" type="xsd:positiveInteger" use="optional" default="1"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="droplist" type="droplist_t"/>
</xsd:schema>

=== szumaster100/backup-storage/Maps/configs/droplist.xml
<?xml version="1.0"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Cleroth (Moblix) -->
<droplist xsi:noNamespaceSchemaLocation="droplist.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<npc_t name="Amphis">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="1000"/>
			<item_t name="SnakeMeat" prob="25"/>
			<item_t name="SnakeSkin" prob="20"/>
			<item_t name="SnakeTeeth" prob="20"/>
			<item_t name="SnakeTongue" prob="17"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="nothing" prob="2500"/>
			<item_t name="NecklaceOfPoisonPro" prob="30"/>
			<item_t name="NecklaceOfSufferent" prob="7"/>
			<item_t name="NecklaceOfMedusa" prob="1"/>
		</tier_t>
	</npc_t>
	<npc_t name="Beholder">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="100"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="nothing" prob="10000"/>
			<item_t name="CancelManual" prob="21"/>
		</tier_t>
	</npc_t>
	<npc_t name="Cannibal-Plant">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="100"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="nothing" prob="500"/>
			<item_t name="RubyRing" prob="500"/>
			<item_t name="RingofWizard" prob="500"/>
			<item_t name="LuckyGoldRing" prob="200"/>
			<item_t name="SapphireRing" prob="200"/>
			<item_t name="RingofMage" prob="200"/>
			<item_t name="EmeraldRing" prob="50"/>
		</tier_t>
	</npc_t>
	<npc_t name="Clay-Golem">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="1000"/>
			<item_t name="LumpofClay" prob="20"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="nothing" prob="8000"/>
			<item_t name="NecklaceOfAirEle" prob="20"/>
			<item_t name="NecklaceOfMerien" prob="20"/>
		</tier_t>
	</npc_t>
	<npc_t name="Cyclops">
		<tier_t type="secondary" prob="998">
			<item_t name="CyclopsMeat" prob="20"/>
			<item_t name="CyclopsHeart" prob="15"/>
			<item_t name="CyclopsEye" prob="10"/>
			<item_t name="CyclopsHandEdge" prob="8"/>
			<item_t name="CyclopsLeather" prob="8"/>
			<item_t name="nothing" prob="1000"/>
		</tier_t>
		<tier_t type="secondary" prob="2">
			<item_t name="MagicNecklace(DF+10)" prob="500"/>
			<item_t name="MagicNecklace(RM10)" prob="500"/>
			<item_t name="RingofOgrepower" prob="15"/>
			<item_t name="MagicNecklace(DM+1)" prob="10"/>
			<item_t name="MagicNecklace(MS10)" prob="10"/>
			<item_t name="NecklaceOfLightPro" prob="5"/>
			<item_t name="NecklaceOfFirePro" prob="5"/>
			<item_t name="CancelManual" prob="1"/>
		</tier_t>
	</npc_t>
	<npc_t name="Dark-Elf">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="100"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="nothing" prob="1500"/>
			<item_t name="DarkElfBow" prob="10"/>
		</tier_t>
	</npc_t>
	<npc_t name="Demon">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="950"/>
			<item_t name="DemonMeat" prob="30"/>
			<item_t name="DemonLeather" prob="20"/>
			<item_t name="DemonEye" prob="15"/>
			<item_t name="DemonHeart" prob="10"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="MassFireStrikeManual" prob="400"/>
			<item_t name="RingofDemonpower" prob="200"/>
			<item_t name="NecklaceOfEfreet" prob="150"/>
			<item_t name="BloodAxe" prob="100"/>
			<item_t name="BloodRapier" prob="100"/>
			<item_t name="BloodSword" prob="50"/>
			<item_t name="BloodyShockW.Manual" prob="30"/>
			<item_t name="DemonSlayer" prob="25"/>
			<item_t name="NecklaceOfXelima" prob="20"/>
			<item_t name="ResurWand(MS.10)" prob="17"/>
			<item_t name="ResurWand(MS.20)" prob="15"/>
			<item_t name="BerserkWand(MS.10)" prob="10"/>
			<item_t name="BerserkWand(MS.20)" prob="5"/>
		</tier_t>
	</npc_t>
	<npc_t name="DireBoar">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="100"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="nothing" prob="700"/>
			<item_t name="GoldenAxe(LLF)" prob="300"/>
		</tier_t>
	</npc_t>
	<npc_t name="Ettin">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="100"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="nothing" prob="1000"/>
			<item_t name="NecklaceOfEfreet" prob="100"/>
			<item_t name="MassFireStrikeManual" prob="80"/>
			<item_t name="BloodAxe" prob="50"/>
			<item_t name="BloodRapier" prob="50"/>
			<item_t name="RingofDemonpower" prob="50"/>
			<item_t name="BloodSword" prob="25"/>
			<item_t name="NecklaceOfMerien" prob="20"/>
			<item_t name="BloodyShockW.Manual" prob="20"/>
			<item_t name="DemonSlayer" prob="15"/>
			<item_t name="BerserkWand(MS.10)" prob="5"/>
			<item_t name="E.S.W.Manual" prob="5"/>
			<item_t name="GiantBattleHammer" prob="4"/>
			<item_t name="BerserkWand(MS.20)" prob="3"/>
		</tier_t>
	</npc_t>
	<npc_t name="Frost">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="100"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="MagicWand(M.Shield)" prob="1000"/>
			<item_t name="RingofGrandMage" prob="50"/>
			<item_t name="IceStormManual" prob="40"/>
			<item_t name="NecklaceOfIcePro" prob="40"/>
			<item_t name="SwordofIceElemental" prob="35"/>
			<item_t name="MagicWand(MS30-LLF)" prob="30"/>
			<item_t name="NecklaceOfIceEle" prob="20"/>
			<item_t name="RingofArchmage" prob="5"/>
			<item_t name="StormBringer" prob="2"/>
		</tier_t>
	</npc_t>
	<npc_t name="Gagoyle">
		<tier_t type="secondary" prob="998">
			<item_t name="nothing" prob="100"/>
		</tier_t>
		<tier_t type="secondary" prob="2">
			<item_t name="RingofDemonpower" prob="20000"/>
			<item_t name="MassFireStrikeManual" prob="8000"/>
			<item_t name="NecklaceOfEfreet" prob="6000"/>
			<item_t name="RingofDragonpower" prob="4000"/>
			<item_t name="BloodyShockW.Manual" prob="1400"/>
			<item_t name="RingoftheXelima" prob="1100"/>
			<item_t name="DarkExecutor" prob="400"/>
			<item_t name="XelimaBlade" prob="300"/>
			<item_t name="XelimaAxe" prob="300"/>
			<item_t name="XelimaRapier" prob="300"/>
			<item_t name="Excaliber" prob="150"/>
			<item_t name="RingoftheAbaddon" prob="70"/>
		</tier_t>
	</npc_t>
	<npc_t name="Giant-Ant">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="300"/>
			<item_t name="AntLeg" prob="17"/>
			<item_t name="AntFeeler" prob="15"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="nothing" prob="2500"/>
			<item_t name="NecklaceOfPoisonPro" prob="30"/>
			<item_t name="NecklaceOfSufferent" prob="7"/>
			<item_t name="NecklaceOfMedusa" prob="1"/>
		</tier_t>
	</npc_t>
	<npc_t name="Giant-Frog">
		<tier_t type="secondary" prob="998">
			<item_t name="nothing" prob="100"/>
		</tier_t>
		<tier_t type="secondary" prob="2">
			<item_t name="nothing" prob="1500"/>
			<item_t name="RubyRing" prob="100"/>
			<item_t name="RingofWizard" prob="100"/>
			<item_t name="RingofOgrepower" prob="100"/>
			<item_t name="LuckyGoldRing" prob="30"/>
			<item_t name="SapphireRing" prob="30"/>
			<item_t name="RingofMage" prob="30"/>
			<item_t name="RingofDemonpower" prob="30"/>
			<item_t name="EmeraldRing" prob="10"/>
		</tier_t>
	</npc_t>
	<npc_t name="Hellbound">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="1000"/>
			<item_t name="HelboundTeeth" prob="9"/>
			<item_t name="HelboundClaw" prob="8"/>
			<item_t name="HelboundLeather" prob="7"/>
			<item_t name="HelboundTail" prob="6"/>
			<item_t name="HelboundHeart" prob="5"/>
			<item_t name="HelboundTongue" prob="4"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="MagicNecklace(DF+10)" prob="150"/>
			<item_t name="MagicNecklace(RM10)" prob="150"/>
			<item_t name="RingofOgrepower" prob="15"/>
			<item_t name="MagicNecklace(DM+1)" prob="10"/>
			<item_t name="MagicNecklace(MS10)" prob="10"/>
			<item_t name="NecklaceOfLightPro" prob="5"/>
			<item_t name="NecklaceOfFirePro" prob="5"/>
		</tier_t>
	</npc_t>
	<npc_t name="Hellclaw">
		<tier_t type="primary" prob="970">
			<item_t name="nothing" prob="1400"/>
			<item_t name="PlateMail(M)" prob="17"/>
			<item_t name="PlateMail(W)" prob="17"/>
			<item_t name="Hauberk(M)" prob="17"/>
			<item_t name="Hauberk(W)" prob="17"/>
			<item_t name="PlateLeggings(M)" prob="17"/>
			<item_t name="PlateLeggings(W)" prob="17"/>
			<item_t name="ChainHose(M)" prob="17"/>
			<item_t name="ChainHose(W)" prob="17"/>
			<item_t name="TowerShield" prob="14"/>
		</tier_t>
		<tier_t type="primary" prob="30">
			<item_t name="StoneOfXelima" prob="750"/>
			<item_t name="StoneOfMerien" prob="350"/>
			<item_t name="ZemstoneofSacrifice" prob="150"/>
		</tier_t>
		<tier_t type="secondary" prob="970">
			<item_t name="MagicNecklace(DF+10)" prob="100"/>
			<item_t name="MagicNecklace(MS10)" prob="100"/>
			<item_t name="MagicNecklace(DM+1)" prob="100"/>
			<item_t name="RingofOgrepower" prob="100"/>
			<item_t name="RingofWizard" prob="100"/>
			<item_t name="RubyRing" prob="100"/>
			<item_t name="MagicWand(M.Shield)" prob="100"/>
		</tier_t>
		<tier_t type="secondary" prob="28">
			<item_t name="nothing" prob="1"/>
			<item_t name="RingofDemonpower" prob="500"/>
			<item_t name="RingofMage" prob="500"/>
			<item_t name="EmeraldRing" prob="500"/>
		</tier_t>
		<tier_t type="secondary" prob="2">
			<item_t name="NecklaceOfIcePro" prob="300"/>
			<item_t name="RingofDragonpower" prob="300"/>
			<item_t name="RingofGrandMage" prob="300"/>
			<item_t name="SwordofIceElemental" prob="200"/>
			<item_t name="NecklaceOfIceEle" prob="50"/>
			<item_t name="MerienShield" prob="25"/>
			<item_t name="NecklaceOfMedusa" prob="3"/>
			<item_t name="NecklaceOfXelima" prob="3"/>
		</tier_t>
	</npc_t>
	<npc_t name="Ice-Golem">
		<tier_t type="secondary" prob="999">
			<item_t name="nothing" prob="100"/>
		</tier_t>
		<tier_t type="secondary" prob="1">
			<item_t name="MagicWand(M.Shield)" prob="1000"/>
			<item_t name="RingofMage" prob="75"/>
			<item_t name="NecklaceOfIcePro" prob="30"/>
